[project]
name = "sischarlesrpg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "aiohappyeyeballs>=2.6.2,<2.8.0",
    "aiohttp>=3.14.0,<4.0.0",
    "aiohttp-jinja2>=1.6",
    "aiosignal>=1.4.0",
    "annotated-doc>=0.0.4",
    "annotated-types>=0.7.0",
    "anyio>=4.13.0",
    "asttokens>=3.0.1",
    "attrs>=26.1.0",
    "cffi>=2.0.0",
    "click>=8.3.2",
    "colorama>=0.4.6",
    "decorator>=5.3.1",
    "emoji>=2.15.0",
    "esper>=3.7",
    "executing>=2.2.1",
    "fastapi>=0.109.0",
    "frozenlist>=1.8.0",
    "greenlet>=3.4.0",
    "h11>=0.16.0",
    "idna>=3.11",
    "iniconfig>=2.3.0",
    "inquirerpy>=0.3.4",
    "ipython>=9.14.1",
    "ipython-pygments-lexers>=1.1.1",
    "jedi>=0.20.0",
    "jinja2>=3.1.6",
    "just-playback>=0.1.8",
    "linkify-it-py>=2.1.0",
    "markdown-it-py>=4.0.0",
    "markupsafe>=3.0.3",
    "matplotlib-inline>=0.2.2",
    "mdit-py-plugins>=0.5.0",
    "mdurl>=0.1.2",
    "msgpack>=1.1.2",
    "multidict>=6.7.1",
    "packaging>=26.0",
    "parso>=0.8.7",
    "pexpect>=4.9.0",
    "pfzy>=0.3.4",
    "platformdirs>=4.9.6",
    "pluggy>=1.6.0",
    "prompt-toolkit>=3.0.52",
    "propcache>=0.5.2",
    "psutil>=7.2.2",
    "ptyprocess>=0.7.0",
    "pure-eval>=0.2.3",
    "pycparser>=3.0",
    "pydantic>=2.14.0a1",
    "pydantic-core>=2.47.0",
    "pyfiglet>=1.0.4",
    "pygments>=2.20.0",
    "pytest>=8.0.0",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
    "shellingham>=1.5.4",
    "sqlalchemy>=2.1.0b1",
    "stack-data>=0.6.3",
    "starlette>=0.47.1,<1.3.1",
    "textual>=8.2.4",
    "textual-dev>=1.8.0",
    "textual-serve>=1.1.3",
    "textual-web>=0.4.2",
    "tinytag>=2.2.1",
    "traitlets>=5.15.1",
    "typer>=0.24.1",
    "typing-extensions>=4.15.0",
    "typing-inspection>=0.4.2",
    "uc-micro-py>=2.0.0",
    "uvicorn>=0.27.0",
    "wcwidth>=0.8.1",
    "yarl>=1.24.2",
]
