[pytest]
pythonpath = ./rpg_api/
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers -ra
markers =
    unit: testes unitários
    integration: testes de integração
    slow: testes lentos
    behavior: testes de comportamento